version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: passfort-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-passfort}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - passfort-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  passfort-api:
    build:
      context: .
      dockerfile: PassFort.API/Dockerfile
    container_name: passfort-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-5123}:5123"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:5123
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB:-passfort};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__Issuer=${JWT_ISSUER:-PassFort}
      - JWT__Audience=${JWT_AUDIENCE:-PassFort}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - passfort-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5123/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  passfort-web:
    build:
      context: .
      dockerfile: passfort-web/Dockerfile
    container_name: passfort-web
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5123}
    depends_on:
      - passfort-api
    networks:
      - passfort-network
    volumes:
      - ./passfort-web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  passfort-network:
    driver: bridge
